version: "3.8"

services:
    backend:
        build: .
        container_name: django_container
        # command: bash -c "python manage.py runserver 0.0.0.0:8000"
        command: bash -c "tail -f /dev/null"
        env_file: .env
        restart: always
        volumes:
            - .:/application
        ports:
            - "8000:8000"
        stdin_open: true
        tty: true
